//
// ApiRegisterResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiRegisterResponse: Codable, JSONEncodable, Hashable {

    public var address: String?
    public var createdAt: String?
    public var email: String?
    public var emailVerified: Bool?
    public var id: Int?
    public var isActive: Bool?
    public var name: String?
    public var phone: String?
    public var phoneVerified: Bool?
    public var role: String?
    /** JWT token (placeholder for now) */
    public var token: String?
    public var uuid: String?

    public init(address: String? = nil, createdAt: String? = nil, email: String? = nil, emailVerified: Bool? = nil, id: Int? = nil, isActive: Bool? = nil, name: String? = nil, phone: String? = nil, phoneVerified: Bool? = nil, role: String? = nil, token: String? = nil, uuid: String? = nil) {
        self.address = address
        self.createdAt = createdAt
        self.email = email
        self.emailVerified = emailVerified
        self.id = id
        self.isActive = isActive
        self.name = name
        self.phone = phone
        self.phoneVerified = phoneVerified
        self.role = role
        self.token = token
        self.uuid = uuid
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case createdAt = "created_at"
        case email
        case emailVerified = "email_verified"
        case id
        case isActive = "is_active"
        case name
        case phone
        case phoneVerified = "phone_verified"
        case role
        case token
        case uuid
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(emailVerified, forKey: .emailVerified)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(isActive, forKey: .isActive)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(phoneVerified, forKey: .phoneVerified)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(token, forKey: .token)
        try container.encodeIfPresent(uuid, forKey: .uuid)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ApiRegisterResponse: Identifiable {}
