//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**
     Login user
     
     - parameter credentials: (body) Login credentials 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func authLoginPost(credentials: ApiLoginRequest, apiResponseQueue: DispatchQueue = GigCoAPIAPI.apiResponseQueue, completion: @escaping ((_ data: ApiLoginResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return authLoginPostWithRequestBuilder(credentials: credentials).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Login user
     - POST /auth/login
     - Authenticate user and return JWT token
     - parameter credentials: (body) Login credentials 
     - returns: RequestBuilder<ApiLoginResponse> 
     */
    open class func authLoginPostWithRequestBuilder(credentials: ApiLoginRequest) -> RequestBuilder<ApiLoginResponse> {
        let localVariablePath = "/auth/login"
        let localVariableURLString = GigCoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: credentials)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiLoginResponse>.Type = GigCoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**
     Register a new user
     
     - parameter user: (body) Registration data 
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func authRegisterPost(user: ApiRegisterRequest, apiResponseQueue: DispatchQueue = GigCoAPIAPI.apiResponseQueue, completion: @escaping ((_ data: ApiRegisterResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return authRegisterPostWithRequestBuilder(user: user).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     Register a new user
     - POST /auth/register
     - Register a new user in the system with email, name and role
     - parameter user: (body) Registration data 
     - returns: RequestBuilder<ApiRegisterResponse> 
     */
    open class func authRegisterPostWithRequestBuilder(user: ApiRegisterRequest) -> RequestBuilder<ApiRegisterResponse> {
        let localVariablePath = "/auth/register"
        let localVariableURLString = GigCoAPIAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: user)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiRegisterResponse>.Type = GigCoAPIAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
