name: GigCoAPI
targets:
  GigCoAPI:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [GigCoAPI]
    info:
      path: ./Info.plist
      version: 1.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
