//
// ApiRegisterRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ApiRegisterRequest: Codable, JSONEncodable, Hashable {

    public var address: String?
    /** For gig workers */
    public var availability: String?
    public var email: String?
    public var latitude: Double?
    public var longitude: Double?
    public var name: String?
    public var phone: String?
    public var placeId: String?
    public var role: String?
    /** For gig workers */
    public var skills: [String]?

    public init(address: String? = nil, availability: String? = nil, email: String? = nil, latitude: Double? = nil, longitude: Double? = nil, name: String? = nil, phone: String? = nil, placeId: String? = nil, role: String? = nil, skills: [String]? = nil) {
        self.address = address
        self.availability = availability
        self.email = email
        self.latitude = latitude
        self.longitude = longitude
        self.name = name
        self.phone = phone
        self.placeId = placeId
        self.role = role
        self.skills = skills
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case availability
        case email
        case latitude
        case longitude
        case name
        case phone
        case placeId = "place_id"
        case role
        case skills
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encodeIfPresent(availability, forKey: .availability)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(phone, forKey: .phone)
        try container.encodeIfPresent(placeId, forKey: .placeId)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(skills, forKey: .skills)
    }
}

